import type { NextPage } from 'next'
import Head from 'next/head'
import db from '../utils/db'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello</h1>
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  await db.connect()
  return {
    props: {
      cac: {}
    }
  }
}

export default Home
