import type { NextPage } from 'next'
import Head from 'next/head'
import db from '../utils/db'
import useSWR from 'swr'
import fetchApi from '../utils/fetchApi'

const Home: NextPage = () => {
  const { data, error } = useSWR('/api/categories', fetchApi)
  console.log('Categories: ', data)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello</h1>
      </main>
    </div>
  )
}

export default Home
